#Grupo PG/GrupoPG_MVC/GrupoPG.WEB/Controllers/OrdemServicosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using PG.Domain;
using PG.Infra.DataContents;

namespace GrupoPG.WEB.Controllers
{
    public class OrdemServicosController : ApiController
    {
        private PGDataContents db = new PGDataContents();

        // GET: api/OrdemServicos
        public IQueryable<OrdemServico> GetOrdemServicoes()
        {
            return db.OrdensServico;
            
        }

        // GET: api/OrdemServicos/5
        [ResponseType(typeof(OrdemServico))]
        public IHttpActionResult GetOrdemServico(int id)
        {
            OrdemServico ordemServico = db.OrdensServico.Find(id);
            if (ordemServico == null)
            {
                return NotFound();
            }

            return Ok(ordemServico);
        }

        // PUT: api/OrdemServicos/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutOrdemServico(int id, OrdemServico ordemServico)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != ordemServico.Id)
            {
                return BadRequest();
            }

            db.Entry(ordemServico).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!OrdemServicoExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/OrdemServicos
        [ResponseType(typeof(OrdemServico))]
        public IHttpActionResult PostOrdemServico(OrdemServico ordemServico)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.OrdensServico.Add(ordemServico);
            db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = ordemServico.Id }, ordemServico);
        }

        // DELETE: api/OrdemServicos/5
        [ResponseType(typeof(OrdemServico))]
        public IHttpActionResult DeleteOrdemServico(int id)
        {
            OrdemServico ordemServico = db.OrdensServico.Find(id);
            if (ordemServico == null)
            {
                return NotFound();
            }

            db.OrdensServico.Remove(ordemServico);
            db.SaveChanges();

            return Ok(ordemServico);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool OrdemServicoExists(int id)
        {
            return db.OrdensServico.Count(e => e.Id == id) > 0;
        }
    }
}

#Grupo PG/GrupoPG_MVC/GrupoPG.WEB/Views/OrdemServico/ListOrdemServico.cshtml
@model IEnumerable<PG.Domain.OrdemServico>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Banco.NomeBanco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContaContabil.NomeConta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Equipe.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PC.ModeloEquipamento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoFixacao.NomeTipoFixacao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoInstalacao.NomeTipoInstalacao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoMaquina.NomeTipoMaquina)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sinalizacao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LocalizacaoMaquina)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomeContato)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TelefoneContato)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Habilitada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ValorTotal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PaUnificado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Defeito)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Serie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataEntrega)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HoraEntrega)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataFinalizacao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DtChegada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HrChegada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DtChegadaTransportadora)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HrChegadaTransportadora)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Banco.NomeBanco)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ContaContabil.NomeConta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Equipe.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PC.ModeloEquipamento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoFixacao.NomeTipoFixacao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoInstalacao.NomeTipoInstalacao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoMaquina.NomeTipoMaquina)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sinalizacao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LocalizacaoMaquina)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NomeContato)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TelefoneContato)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Habilitada)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ValorTotal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PaUnificado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Defeito)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Serie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataEntrega)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HoraEntrega)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataFinalizacao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DtChegada)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HrChegada)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DtChegadaTransportadora)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HrChegadaTransportadora)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

#Grupo PG/GrupoPG_MVC/GrupoPG.WEB/Views/OrdemServico/OrdemServico.cshtml
@model PG.Domain.OrdemServico


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OrdemServico</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.BancoId, "BancoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BancoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BancoId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Sinalizacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sinalizacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sinalizacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocalizacaoMaquina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LocalizacaoMaquina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LocalizacaoMaquina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NomeContato, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeContato, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeContato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelefoneContato, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelefoneContato, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelefoneContato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Habilitada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Habilitada)
                    @Html.ValidationMessageFor(model => model.Habilitada, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorTotal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorTotal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorTotal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaUnificado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaUnificado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaUnificado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Defeito, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Defeito, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Defeito, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.ContaContabilId, "ContaContabilId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ContaContabilId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ContaContabilId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Serie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Serie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Serie, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.TipoMaquinaId, "TipoMaquinaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipoMaquinaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoMaquinaId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.TipoFixacaoID, "TipoFixacaoID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipoFixacaoID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoFixacaoID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoInstalacaoId, "TipoInstalacaoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipoInstalacaoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoInstalacaoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EquipeId, "EquipeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EquipeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EquipeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PCId, "PCId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PCId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PCId, "", new { @class = "text-danger" })
            </div>
        </div*@>

        <div class="form-group">
            @Html.LabelFor(model => model.DataEntrega, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataEntrega, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataEntrega, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoraEntrega, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoraEntrega, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoraEntrega, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataFinalizacao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataFinalizacao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataFinalizacao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DtChegada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DtChegada, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DtChegada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HrChegada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HrChegada, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HrChegada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DtChegadaTransportadora, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DtChegadaTransportadora, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DtChegadaTransportadora, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HrChegadaTransportadora, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HrChegadaTransportadora, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HrChegadaTransportadora, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />@Html.ActionLink("Salvar", "OrdemServicos", "OrdemServico")
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}